language: go
go:
  - 1.9.x
env:
  - TESTARGS="-cover -v"
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get -u github.com/golang/dep/cmd/dep
script:
  - make test
